import type {
  College,
  GradProgram,
  Scholarship,
  Prediction,
  SearchPayload,
} from "./types";

/**
 * Student profile — the context object injected into every AI prompt. In
 * production this becomes the user's record plus computed readiness signals.
 */
export const PROFILE =
  "Student: Marlon Sandoval, rising 9th grader (Class of 2030) at Cuthbertson High School in Waxhaw, North Carolina. No GPA yet — entering 9th grade this fall. Home state for residency / in-state tuition: North Carolina. Goal: become a biomedical AI researcher (genetics + machine learning). Activities: volleyball, Scouting America, CrossFit. Interests: genetics, genomics, neuroscience, AI/ML. Budget-conscious, needs affordability + merit aid. Long-range planner currently building foundations.";

export const STUDENT = {
  fullName: "Marlon Sandoval",
  firstName: "Marlon",
  initials: "MS",
  classLine: "Class of 2030",
  yearAheadLine: "Freshman year ahead",
  daysToAppLine: "~1,200 days to your first application",
};

export const COLLEGES: College[] = [
  {
    id: "utexas",
    name: "UT Austin",
    location: "Austin, TX",
    type: "Public · Very large",
    size: "42,000 undergrad",
    accept: "31%",
    sat: "1230–1480",
    deadline: "RD Dec 1",
    match: 78,
    band: "Target",
    bandColor: "aB",
    summary:
      "A top public for computational biology and CS — but out-of-state for you, so no auto-admit and no resident price. Worth pursuing only if the program fit clearly beats your NC publics.",
    tuition: "$41K out-of-state",
    net: "~$38K/yr est. (OOS)",
    aid: "Limited need-based aid for non-Texas residents",
    admitScore: 55,
    affordScore: 48,
    academicScore: 84,
    campusScore: 82,
    careerScore: 85,
    majors: ["Computer Science", "Biology", "Neuroscience", "Biochemistry", "Human Development"],
    research:
      "Dell Medical + Bioinformatics; Freshman Research Initiative places first-years in real labs.",
    gradRate: "88% 6-yr",
    salary: "$78K median early career (CS)",
    employers: ["Dell", "Texas Medical Center", "NIH", "Google"],
    pros: [
      "Freshman Research Initiative = labs from year one",
      "Strong computational biology + CS",
      "Large alumni network in tech",
    ],
    cons: ["Out-of-state price is far above your NC publics", "Very large classes early on"],
    risks: [
      "No auto-admit for out-of-state applicants — admission is genuinely competitive",
      "OOS affordability is the real hurdle without merit aid",
    ],
    actions: [
      "Only pursue if it clearly beats UNC/NC State on fit",
      "Run the OOS net price calculator with your numbers",
      "Look for merit scholarships that offset the OOS cost",
    ],
  },
  {
    id: "unc",
    name: "UNC Chapel Hill",
    location: "Chapel Hill, NC",
    type: "Public · Large",
    size: "~20,000 undergrad",
    accept: "15% overall · ~43% in-state",
    sat: "1400–1530",
    deadline: "EA Oct 15 · RD Jan 15",
    match: 90,
    band: "Target",
    bandColor: "aB",
    summary:
      "Your in-state anchor: a genetics and genomics powerhouse with unusually early undergraduate lab access, that meets full demonstrated need for North Carolina residents like you.",
    tuition: "$9.0K in-state",
    net: "~$11K/yr est. (in-state, after aid)",
    aid: "Meets full need for NC residents; Carolina Covenant for low-income families",
    admitScore: 62,
    affordScore: 90,
    academicScore: 92,
    campusScore: 81,
    careerScore: 84,
    majors: ["Genetics", "Biology", "Computer Science", "Neuroscience", "Biostatistics"],
    research:
      "Carolina Center for Genome Sciences; undergrads join labs as early as sophomore year via OUR.",
    gradRate: "91% 6-yr",
    salary: "$70K median early career",
    employers: ["NIH", "Genentech", "Epic", "Duke Health"],
    pros: [
      "Elite genetics + genomics research",
      "Real, early undergrad lab access",
      "In-state price plus full need met for NC residents",
    ],
    cons: ["CS major admission is competitive within the school", "Large intro classes early on"],
    risks: [
      "In-state admission is strong but CS is selective — keep grades high",
      "Honors Carolina adds an extra application",
    ],
    actions: ["Lock in as your in-state Target", "Apply EA (Oct 15)", "Email the Genome Sciences lab next summer"],
  },
  {
    id: "ncstate",
    name: "NC State",
    location: "Raleigh, NC",
    type: "Public · Very large",
    size: "~28,400 undergrad",
    accept: "42% overall · higher in-state",
    sat: "1300–1470",
    deadline: "EA Nov 1 · RD Jan 15",
    match: 88,
    band: "Likely",
    bandColor: "aA",
    summary:
      "Your most affordable in-state pick: a Research Triangle land-grant with a rare standalone undergraduate Genetics degree and a top bioinformatics center — strong bio + computing fit at the resident price.",
    tuition: "$9.1K in-state",
    net: "~$12K/yr est. (in-state, after aid)",
    aid: "69% receive aid; Pack Promise meets full need for low-income NC residents",
    admitScore: 78,
    affordScore: 90,
    academicScore: 84,
    campusScore: 84,
    careerScore: 83,
    majors: ["Genetics", "Bioinformatics", "Computer Science", "Biological Sciences", "Statistics"],
    research:
      "Bioinformatics Research Center plus a dedicated B.S. in Genetics; deep genomics + data-science labs alongside Duke and UNC in the Research Triangle.",
    gradRate: "80% 6-yr",
    salary: "$68K median early career",
    employers: ["SAS", "IBM", "Biogen", "Red Hat", "BASF"],
    pros: [
      "One of the few standalone undergraduate Genetics B.S. programs",
      "Top-tier Bioinformatics Research Center",
      "Research Triangle access to Duke + UNC labs",
      "In-state price with Pack Promise need coverage",
    ],
    cons: [
      "Very large — early classes can feel impersonal",
      "CS and engineering admits run tougher than the overall rate",
    ],
    risks: [
      "CS and engineering are more competitive than the 42% overall rate",
      "Apply EA to lock in your strongest consideration",
    ],
    actions: [
      "Apply EA by Nov 1 as your affordable Likely school",
      "Explore the Genetics B.S. and Bioinformatics Research Center",
      "Compare net price against UNC",
    ],
  },
  {
    id: "ucsd",
    name: "UC San Diego",
    location: "La Jolla, CA",
    type: "Public · Very large",
    size: "33,000 undergrad",
    accept: "25%",
    sat: "1300–1520",
    deadline: "Nov 1–30 (UC app)",
    match: 84,
    band: "Target",
    bandColor: "aB",
    summary:
      "A bioinformatics leader where biology and machine learning genuinely converge — exactly the intersection your goal lives at — with a strong undergraduate research culture.",
    tuition: "$14K in-state · $44K out",
    net: "~$31K/yr est. (OOS)",
    aid: "Limited aid for non-California residents",
    admitScore: 38,
    affordScore: 58,
    academicScore: 91,
    campusScore: 78,
    careerScore: 88,
    majors: ["Bioinformatics", "Computer Science", "Biology", "Cognitive Science", "Data Science"],
    research: "Halıcıoğlu Data Science Institute + Bioengineering; heavy genomics + ML crossover.",
    gradRate: "87% 6-yr",
    salary: "$84K median early career (CS/DS)",
    employers: ["Illumina", "Qualcomm", "Salk Institute", "Google"],
    pros: [
      "Best biology + ML crossover on your list",
      "Top bioinformatics faculty",
      "Pipeline to Illumina and Salk",
    ],
    cons: ["Pricey for out-of-state without aid", "Large, decentralized college system"],
    risks: [
      "OOS affordability is the main risk — weigh merit options",
      "Capped majors can be hard to switch into",
    ],
    actions: ["Save as a Target", "Compare OOS net price vs UNC", "Explore the bioinformatics major requirements"],
  },
  {
    id: "berkeley",
    name: "UC Berkeley",
    location: "Berkeley, CA",
    type: "Public · Very large",
    size: "~32,000 undergrad",
    accept: "11%",
    sat: "1330–1530",
    deadline: "Nov 1–30 (UC app)",
    match: 83,
    band: "Reach",
    bandColor: "rose",
    summary:
      "The birthplace of CRISPR gene editing and a top-tier home for computing — the Innovative Genomics Institute plus elite EECS put your genetics-plus-AI goal at the exact center. Out-of-state for you, so cost and admit odds are the things to weigh.",
    tuition: "$15K in-state · $49K out",
    net: "~$40K/yr est. (OOS)",
    aid: "Little need-based aid for non-California residents",
    admitScore: 16,
    affordScore: 42,
    academicScore: 96,
    campusScore: 87,
    careerScore: 93,
    majors: [
      "Molecular & Cell Biology",
      "Computer Science",
      "Bioengineering",
      "Data Science",
      "Electrical Eng. & Computer Sciences",
    ],
    research:
      "Innovative Genomics Institute (Jennifer Doudna / CRISPR); URAP places undergrads in labs as early as freshman year.",
    gradRate: "92% 6-yr",
    salary: "$92K median early career",
    employers: ["Genentech", "Google", "Chan Zuckerberg Biohub", "Illumina"],
    pros: [
      "Innovative Genomics Institute — CRISPR research at the source",
      "Top-tier EECS paired with molecular biology",
      "URAP research access + Bay Area biotech pipeline",
    ],
    cons: [
      "~11% admit rate — a reach for out-of-state applicants",
      "Out-of-state cost is among the highest on your list",
      "Very large; early classes can feel impersonal",
    ],
    risks: [
      "OOS aid is minimal — weigh affordability hard against your NC publics",
      "Capped majors like CS/EECS are difficult to enter or switch into",
    ],
    actions: [
      "Keep as a Reach and apply via the UC app",
      "Highlight any genetics research in your Personal Insight Questions",
      "Run the OOS net price calculator before investing time",
    ],
  },
  {
    id: "uga",
    name: "University of Georgia",
    location: "Athens, GA",
    type: "Public · Large",
    size: "30,200 undergrad",
    accept: "37%",
    sat: "1240–1420",
    deadline: "EA Oct 15 · RD Jan 1",
    match: 76,
    band: "Target",
    bandColor: "aB",
    summary:
      "Georgia's flagship pairs a rare standalone Genetics department with strong merit aid — a friendly Target where early lab work and low debt are both realistic.",
    tuition: "$12K in-state · $31K out",
    net: "~$20K/yr est. (OOS)",
    aid: "Strong merit; Foundation Fellowship for top applicants",
    admitScore: 48,
    affordScore: 70,
    academicScore: 82,
    campusScore: 85,
    careerScore: 79,
    majors: ["Genetics", "Biology", "Computer Science", "Biochemistry & Molecular Biology", "Cognitive Science"],
    research:
      "Department of Genetics (one of few standalone in the US); CURO undergraduate research.",
    gradRate: "87% 6-yr",
    salary: "$66K median early career",
    employers: ["CDC", "Merck", "Boehringer Ingelheim", "Piedmont Health"],
    pros: [
      "Rare standalone Genetics department",
      "CURO guarantees a research pathway",
      "Generous merit scholarships",
    ],
    cons: ["OOS admission is competitive", "Less AI crossover than the UCs"],
    risks: ["Foundation Fellowship is highly selective", "Apply EA for the best scholarship odds"],
    actions: [
      "Apply Early Action for merit review",
      "Explore the CURO research program",
      "Email the Genetics department about labs",
    ],
  },
  {
    id: "duke",
    name: "Duke University",
    location: "Durham, NC",
    type: "Private · Medium",
    size: "6,600 undergrad",
    accept: "6%",
    sat: "1490–1570",
    deadline: "ED Nov 1 · RD Jan 2",
    match: 74,
    band: "Reach",
    bandColor: "rose",
    summary:
      "A genomics and biomedical-engineering leader in the Carolinas with no-loan aid that meets full need — a high reach worth one strong, well-aimed application.",
    tuition: "$63K sticker",
    net: "~$8K/yr est. (your income band)",
    aid: "Meets full need; no loans",
    admitScore: 11,
    affordScore: 86,
    academicScore: 96,
    campusScore: 88,
    careerScore: 94,
    majors: [
      "Biology",
      "Computer Science",
      "Genome Sciences & Computational Biology",
      "Biomedical Engineering",
      "Statistical Science",
    ],
    research:
      "Center for Genomic & Computational Biology; undergrads join labs via Bass Connections.",
    gradRate: "95% 6-yr",
    salary: "$92K median early career",
    employers: ["Duke Health", "Genentech", "Google", "IQVIA"],
    pros: [
      "Elite genomics + computational biology",
      "Excellent need-based aid",
      "Bass Connections research teams",
    ],
    cons: ["~6% admit rate — a reach", "High-pressure pre-professional culture"],
    risks: ["ED boosts odds but limits aid comparison", "Reach odds apply even with strong stats"],
    actions: [
      "Decide if binding ED is worth it",
      "Read up on the Genome Sciences program",
      "Keep as one of your two stretch applications",
    ],
  },
  {
    id: "harvard",
    name: "Harvard University",
    location: "Cambridge, MA",
    type: "Private · Medium",
    size: "7,200 undergrad",
    accept: "3%",
    sat: "1490–1580",
    deadline: "REA Nov 1 · RD Jan 1",
    match: 70,
    band: "Reach",
    bandColor: "rose",
    summary:
      "A dream-tier reach where genetics and AI research run deep, and need-based aid can make it nearly free for your family — admission is the only hurdle.",
    tuition: "$59K sticker",
    net: "~$4K/yr est. (your income band)",
    aid: "Free tuition under $85K income; no loans",
    admitScore: 8,
    affordScore: 92,
    academicScore: 98,
    campusScore: 90,
    careerScore: 97,
    majors: [
      "Molecular & Cellular Biology",
      "Computer Science",
      "Human Developmental & Regenerative Biology",
      "Statistics",
      "Bioengineering",
    ],
    research:
      "Broad Institute (with MIT); Department of Genetics at Harvard Medical School.",
    gradRate: "97% 6-yr",
    salary: "$95K median early career",
    employers: ["Broad Institute", "Mass General Brigham", "Google", "startups"],
    pros: [
      "World-leading genetics via the Broad Institute",
      "Among the best need-based aid anywhere",
      "Unrivaled network and resources",
    ],
    cons: ["~3% admit rate — an extreme reach", "Admission is unpredictable for everyone"],
    risks: ["Odds are low regardless of strength", "Never build your plan around this school"],
    actions: [
      "Keep as an aspirational Reach",
      "Pour energy into a standout research project",
      "Apply only if it does not crowd out targets",
    ],
  },
  {
    id: "ncat",
    name: "North Carolina A&T State University",
    location: "Greensboro, NC",
    type: "Public · Large (HBCU)",
    size: "11,200 undergrad",
    accept: "57%",
    sat: "1010–1150",
    deadline: "Rolling · priority Feb 1",
    match: 81,
    band: "Likely",
    bandColor: "aA",
    summary:
      "The nation's largest HBCU and a STEM powerhouse, close to home with strong aid and a clear research pathway — a confident Likely that values exactly your strengths.",
    tuition: "$6.5K in-state · $20K out",
    net: "~$14K/yr est. (OOS)",
    aid: "Strong need + merit aid; Aggie scholarships",
    admitScore: 68,
    affordScore: 80,
    academicScore: 76,
    campusScore: 86,
    careerScore: 80,
    majors: ["Biology", "Computer Science", "Bioengineering", "Chemistry", "Data Science"],
    research:
      "NSF/NIH-funded undergraduate research; nationally ranked for STEM degrees awarded to Black students.",
    gradRate: "58% 6-yr",
    salary: "$64K median early career",
    employers: ["NASA", "Boeing", "Merck", "GSK"],
    pros: [
      "Top HBCU for STEM with real research funding",
      "Affordable with strong scholarships",
      "Supportive, community-driven campus",
    ],
    cons: ["Less genetics-specific depth than research universities", "Lower published test-score band"],
    risks: ["Apply by the Feb 1 priority date for best aid", "Confirm research openings in your field"],
    actions: [
      "Apply early for priority scholarship review",
      "Ask about NSF-funded undergrad research",
      "Keep as a strong, affordable Likely",
    ],
  },
];

export const GRAD_PROGRAMS: GradProgram[] = [
  {
    id: "gunc",
    name: "UNC Chapel Hill — MS Bioinformatics & Computational Biology",
    location: "Chapel Hill, NC",
    type: "Master's · STEM",
    size: "~40/cohort",
    accept: "22%",
    match: 91,
    band: "Likely",
    bandColor: "aA",
    affordScore: 78,
    academicScore: 92,
    careerScore: 85,
  },
  {
    id: "ggt",
    name: "Georgia Tech — MS Computational Science & Engineering (OMSCS)",
    location: "Atlanta, GA",
    type: "Master's · Online-friendly",
    size: "Large cohort",
    accept: "65%",
    match: 84,
    band: "Target",
    bandColor: "gold",
    affordScore: 88,
    academicScore: 82,
    careerScore: 83,
  },
  {
    id: "gjhu",
    name: "Johns Hopkins — MS/PhD Genetic Medicine",
    location: "Baltimore, MD",
    type: "PhD · Funded",
    size: "~15/cohort",
    accept: "12%",
    match: 79,
    band: "Reach",
    bandColor: "rose",
    affordScore: 70,
    academicScore: 96,
    careerScore: 88,
  },
  {
    id: "gstan",
    name: "Stanford — MS Computer Science (AI Track)",
    location: "Stanford, CA",
    type: "Master's · STEM",
    size: "~180/cohort",
    accept: "8%",
    match: 88,
    band: "Reach",
    bandColor: "rose",
    affordScore: 55,
    academicScore: 97,
    careerScore: 95,
  },
  {
    id: "gupenn",
    name: "Penn — MS Genomics and Computational Biology",
    location: "Philadelphia, PA",
    type: "Master's · STEM",
    size: "~25/cohort",
    accept: "28%",
    match: 85,
    band: "Target",
    bandColor: "aB",
    affordScore: 65,
    academicScore: 94,
    careerScore: 91,
  },
  {
    id: "gcolu",
    name: "Columbia — MS Data Science",
    location: "New York, NY",
    type: "Master's · STEM",
    size: "~120/cohort",
    accept: "35%",
    match: 82,
    band: "Target",
    bandColor: "aB",
    affordScore: 60,
    academicScore: 93,
    careerScore: 94,
  },
];

export const SCHOLARSHIPS: Scholarship[] = [
  {
    id: "qb",
    name: "QuestBridge National College Match",
    amount: "Full 4-yr ride",
    deadline: "Sep 2027 (junior)",
    match: 79,
    tag: "Essay",
    soon: false,
    note: "Matches high-achieving, low/middle-income students to 50+ partner colleges.",
  },
  {
    id: "gleaf",
    name: "Golden LEAF Scholarship",
    amount: "$3,000/yr (up to $12K)",
    deadline: "Feb (annual)",
    match: 81,
    tag: "No essay",
    soon: true,
    note: "For North Carolina students from rural counties attending an NC college — a clean fit for your in-state profile.",
  },
  {
    id: "gates",
    name: "The Gates Scholarship",
    amount: "Full cost of attendance",
    deadline: "Sep 2028 (senior)",
    match: 74,
    tag: "Essay",
    soon: false,
    note: "For Pell-eligible minority students with leadership and academic strength.",
  },
  {
    id: "coke",
    name: "Coca-Cola Scholars",
    amount: "$20,000",
    deadline: "Oct 2028 (senior)",
    match: 72,
    tag: "Essay",
    soon: false,
    note: "Leadership + service award — start building your activity record now.",
  },
  {
    id: "regeneron",
    name: "Regeneron Science Talent Search",
    amount: "Up to $250,000",
    deadline: "Nov 2028 (senior)",
    match: 68,
    tag: "Project",
    soon: false,
    note: "Rewards original research — begin a genetics project this year.",
  },
  {
    id: "davidson",
    name: "Davidson Fellows",
    amount: "Up to $50,000",
    deadline: "Feb (annual)",
    match: 64,
    tag: "Project",
    soon: true,
    note: "Project-based; submit significant STEM work as it matures.",
  },
];

export const PREDICTIONS: Prediction[] = [
  {
    key: "admit",
    label: "Admission readiness",
    value: "34%",
    confidence: "0.71",
    trend: "▲ building",
    reason:
      "Strong GPA foundation; research experience and test scores are the levers that will lift target-school odds most.",
  },
  {
    key: "schol",
    label: "Scholarship readiness",
    value: "41%",
    confidence: "0.66",
    trend: "▲ rising",
    reason:
      "Six awards already matched; a stronger leadership and service record is the main gap to close.",
  },
  {
    key: "grad",
    label: "Graduation readiness",
    value: "88%",
    confidence: "0.83",
    trend: "steady",
    reason:
      "Course rigor and GPA trajectory point to a high likelihood of completing a STEM degree on time.",
  },
  {
    key: "research",
    label: "Research readiness",
    value: "28%",
    confidence: "0.62",
    trend: "▲ building",
    reason: "Lab exposure this summer is the single highest-leverage step on your entire timeline.",
  },
  {
    key: "career",
    label: "Career readiness",
    value: "31%",
    confidence: "0.58",
    trend: "▲ early",
    reason:
      "Expected for your stage; internships and a visible portfolio will move this fastest in junior year.",
  },
  {
    key: "intern",
    label: "Internship readiness",
    value: "24%",
    confidence: "0.55",
    trend: "▲ early",
    reason: "Build foundational skills first, then target structured sophomore-summer programs.",
  },
];

export const DEFAULT_SOPH: string[] = [
  "Biology + intro coding (honors track)",
  "Join Science Olympiad",
  "Build strong study habits — aim for a high GPA",
  "Genome reading list + a free intro biology MOOC",
  "Explore a summer science enrichment program",
  "Start a curiosity journal of research questions",
];

export const FRESHMAN_DONE: string[] = [
  "Foundations of Biology + honors math",
  "Joined Science Olympiad",
  "Started a genetics reading list",
  "Set up a curiosity journal",
];

export const JUNIOR_PLANNED: string[] = [
  "AP Biology + AP Computer Science",
  "Summer research placement / lab internship",
  "PSAT/NMSQT + begin SAT prep",
  "Grow science-fair project toward Regeneron STS",
];

export const SENIOR_PLANNED: string[] = [
  "Finalize college list + write applications",
  "Apply Early Action to UNC / NC State",
  "Submit FAFSA + scholarship applications",
  "Publish or present research findings",
];

export const FALLBACK_SEARCH: SearchPayload = {
  summary:
    "Based on your genetics-plus-AI goal and need for affordability, I'd anchor on public research universities with strong genomics and undergraduate research access. These five balance fit, cost, and admissions reach for a strong sophomore profile.",
  results: [
    { type: "College", name: "UNC Chapel Hill", meta: "Chapel Hill, NC", match: 88, note: "Top-tier genetics, generous aid, undergrads in labs early." },
    { type: "College", name: "UC San Diego", meta: "La Jolla, CA", match: 84, note: "Bioinformatics powerhouse; strong CS + biology crossover." },
    { type: "College", name: "Univ. of Wisconsin–Madison", meta: "Madison, WI", match: 81, note: "Deep genomics center, affordable for strong applicants." },
    { type: "Scholarship", name: "QuestBridge Match", meta: "Full ride · partner schools", match: 79, note: "Free path to 50+ selective colleges; apply junior year." },
    { type: "Faculty", name: "Dr. A. Reyes — Genomics Lab", meta: "UNC · accepts undergrads", match: 76, note: "Studies gene regulation with ML; mentors early students." },
  ],
  actions: [
    "Save UNC and UC San Diego to your college list",
    "Add QuestBridge to your scholarship tracker",
    "Draft an intro email to Dr. Reyes' lab for next summer",
  ],
};

export const FALLBACK_CMDK =
  "I'm offline right now, but here's the gist: as a rising freshman aiming at biomedical AI research, focus this year on (1) a hands-on lab/summer program, (2) honors Bio + a genomics MOOC to fuse biology with ML, and (3) a science-fair project you can grow into research. I'll turn any of these into a tracked plan.";

export const FALLBACK_NB =
  "Here's how I'd approach it:\n• This summer — a hands-on lab or the Rice Bioscience Academy\n• Fall — honors Bio plus a genomics MOOC to fuse biology with ML\n• Start a small genetics science-fair project you can grow into research\n• I'll track every deadline and nudge you along the way.\n\n(AI is offline right now — this is a sample plan.)";

export const FALLBACK_INSIGHT =
  "This is a strong, realistic fit for your genetics + AI goal — prioritize it and I'll build the timeline and reminders around it. (AI offline; showing guidance.)";

export const EXAMPLE_QUERIES = [
  "Best affordable colleges for genetics + AI research",
  "Summer research programs for a rising freshman",
  "Scholarships I can start preparing for now",
  "How do I get into a lab early in high school?",
];

export const CMDK_SUGGESTIONS = [
  "Plan my summer for research readiness",
  "Which colleges fit my genetics + AI goal?",
  "What should I focus on this school year?",
  "Find scholarships I can win as a freshman",
];

export const AGENTS_AT_WORK = [
  { agent: "Admissions Advisor", status: "Re-scored 3 target schools against your latest profile" },
  { agent: "Research Assistant", status: "Matched 2 summer labs that accept early high-schoolers" },
  { agent: "Scholarship Strategist", status: "Queued 6 new awards worth $42K to your tracker" },
];
